Validate base_value
Validate that base_value is not None before calling the recursive function.

If the value is None, in the next call of the function the line `base_value = original_data[field]` will fail with

```
  File "/code/example/venv/lib/python3.9/site-packages/grow/pods/pods.py", line 869, in preprocess
    preprocessor.run(build=build)
  File "/code/example/extensions/kintaro/kintaro.py", line 688, in run
    entries_with_bindings = self.download_and_group_entries(self.config.bind)
  File "/code/example/extensions/kintaro/kintaro.py", line 582, in download_and_group_entries
    grouped_entries = self._group_entries(
  File "/code/example/extensions/kintaro/kintaro.py", line 265, in _group_entries
    document.add_field_data(fields, locale=locale)
  File "/code/example/extensions/kintaro/kintaro.py", line 153, in add_field_data
    self._fields = GroupedEntry.merge_data(
  File "/code/example/extensions/kintaro/kintaro.py", line 117, in merge_data
    final_data[field] = GroupedEntry.merge_data(
  File "/code/example/extensions/kintaro/kintaro.py", line 117, in merge_data
    final_data[field] = GroupedEntry.merge_data(
  File "/code/example/extensions/kintaro/kintaro.py", line 111, in merge_data
    base_value = original_data[field]
TypeError: 'NoneType' object is not subscriptable
```